### ISSUE TITLE
Using the built framework outside the current Xcode project

### ISSUE THREAD

**Issue by garethcurtis** [benasher44/CocoaPodsLibExample#1]
Hi there,

This example you've made is great but can I ask please, if I've understood this correctly, how do you then use the framework outside of the original project? Surely one of the main benefits of packaging code up in a framework is then to distribute to others but whenever I try to use this in another project (i.e. not as a subproject - just the framework dragged into another project) I run into the image not found error.

dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
  Referenced from: /Users/garethcurtis/Library/Developer/CoreSimulator/Devices/15D34B38-02CF-4A6C-8F2D-A1E94FD87EDF/data/Containers/Bundle/Application/7EB604C0-8225-4AB4-B683-1751B33422A7/PodFrameworkTest.app/Frameworks/SampleFramework.framework/SampleFramework
  Reason: image not found

If I build and run the app in the example project, I can see Lumberjack is added as a framework alongside SampleFramework in the Frameworks folder, but as soon as I include this in an external project, only SampleFramework exists and I get the above error. What am I missing please?

I think Target Dependency might be the key but like I say, if I'm not using a subproject then I can't use it.

Thanks very much,

Gareth.

**Comment by garethcurtis** [comment]
My Runpath Search Paths is @executable_path/Frameworks

**Comment by benasher44** [comment]
Hi! I’m glad you’ve found this useful! This is meant to be used for developing on a framework project that is distributed using CocoaPods. In this case, you’d typically create a podspec that has CocoaLumberjack as a dependency. The , you’d use CocoaPods to install the pod. Does that make sense? This example isn’t intended for developing a framework that would initially be managed by CocoaPods but would then be packaged up and distributed on its own. Hope that helps clear things up!

**Comment by garethcurtis** [comment]
Hey thanks. Yes, I realised that afterwards. You're right, I should use Cocoapods to manage the dependencies and third party libraries I'm using, rather than trying to get them into the framework itself! That's what I ended up doing. Thanks again - this was a useful start for me.

**Comment by benasher44** [comment]
No problem! Glad you found this helpful!
